# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.hardware import hardware_pb2 as api_dot_hardware_dot_hardware__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/hardware/hardware_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HardwareServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHardwareResources = channel.unary_unary(
                '/haas.hardware.v1.HardwareService/GetHardwareResources',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_hardware_dot_hardware__pb2.HardwareListResponse.FromString,
                _registered_method=True)
        self.RequestHardware = channel.unary_unary(
                '/haas.hardware.v1.HardwareService/RequestHardware',
                request_serializer=api_dot_hardware_dot_hardware__pb2.HardwareRequest.SerializeToString,
                response_deserializer=api_dot_hardware_dot_hardware__pb2.Hardware.FromString,
                _registered_method=True)
        self.ReturnHardware = channel.unary_unary(
                '/haas.hardware.v1.HardwareService/ReturnHardware',
                request_serializer=api_dot_hardware_dot_hardware__pb2.HardwareRequest.SerializeToString,
                response_deserializer=api_dot_hardware_dot_hardware__pb2.Hardware.FromString,
                _registered_method=True)
        self.GetProjectHardware = channel.unary_unary(
                '/haas.hardware.v1.HardwareService/GetProjectHardware',
                request_serializer=api_dot_hardware_dot_hardware__pb2.ProjectRequest.SerializeToString,
                response_deserializer=api_dot_hardware_dot_hardware__pb2.HardwareListResponse.FromString,
                _registered_method=True)


class HardwareServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHardwareResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HardwareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHardwareResources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareResources,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api_dot_hardware_dot_hardware__pb2.HardwareListResponse.SerializeToString,
            ),
            'RequestHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHardware,
                    request_deserializer=api_dot_hardware_dot_hardware__pb2.HardwareRequest.FromString,
                    response_serializer=api_dot_hardware_dot_hardware__pb2.Hardware.SerializeToString,
            ),
            'ReturnHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnHardware,
                    request_deserializer=api_dot_hardware_dot_hardware__pb2.HardwareRequest.FromString,
                    response_serializer=api_dot_hardware_dot_hardware__pb2.Hardware.SerializeToString,
            ),
            'GetProjectHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectHardware,
                    request_deserializer=api_dot_hardware_dot_hardware__pb2.ProjectRequest.FromString,
                    response_serializer=api_dot_hardware_dot_hardware__pb2.HardwareListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'haas.hardware.v1.HardwareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('haas.hardware.v1.HardwareService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HardwareService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHardwareResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/haas.hardware.v1.HardwareService/GetHardwareResources',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api_dot_hardware_dot_hardware__pb2.HardwareListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/haas.hardware.v1.HardwareService/RequestHardware',
            api_dot_hardware_dot_hardware__pb2.HardwareRequest.SerializeToString,
            api_dot_hardware_dot_hardware__pb2.Hardware.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/haas.hardware.v1.HardwareService/ReturnHardware',
            api_dot_hardware_dot_hardware__pb2.HardwareRequest.SerializeToString,
            api_dot_hardware_dot_hardware__pb2.Hardware.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/haas.hardware.v1.HardwareService/GetProjectHardware',
            api_dot_hardware_dot_hardware__pb2.ProjectRequest.SerializeToString,
            api_dot_hardware_dot_hardware__pb2.HardwareListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
