# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/hardware/hardware.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/hardware/hardware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pi/hardware/hardware.proto\x12\x10haas.hardware.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\x12GetHardwareRequest\x12\x11\n\thw_set_id\x18\x01 \x01(\t\"J\n\x0fHardwareRequest\x12\x11\n\thw_set_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\r\"\x95\x01\n\x08Hardware\x12\x11\n\thw_set_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\r\x12\x11\n\tavailable\x18\x04 \x01(\r\x12\x13\n\x0b\x63hecked_out\x18\x05 \x01(\r\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"I\n\x14HardwareListResponse\x12\x31\n\rhardware_sets\x18\x01 \x03(\x0b\x32\x1a.haas.hardware.v1.Hardware\"$\n\x0eProjectRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"{\n\x15ProjectResourceStatus\x12\x11\n\thw_set_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1c\n\x14quantity_checked_out\x18\x03 \x01(\r\x12\x11\n\tavailable\x18\x04 \x01(\r\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\r\"[\n\x1dProjectResourceStatusResponse\x12:\n\tresources\x18\x01 \x03(\x0b\x32\'.haas.hardware.v1.ProjectResourceStatus2\xd6\x03\n\x0fHardwareService\x12X\n\x14GetHardwareResources\x12\x16.google.protobuf.Empty\x1a&.haas.hardware.v1.HardwareListResponse\"\x00\x12Q\n\x0bGetHardware\x12$.haas.hardware.v1.GetHardwareRequest\x1a\x1a.haas.hardware.v1.Hardware\"\x00\x12R\n\x0fRequestHardware\x12!.haas.hardware.v1.HardwareRequest\x1a\x1a.haas.hardware.v1.Hardware\"\x00\x12Q\n\x0eReturnHardware\x12!.haas.hardware.v1.HardwareRequest\x1a\x1a.haas.hardware.v1.Hardware\"\x00\x12o\n\x18GetProjectResourceStatus\x12 .haas.hardware.v1.ProjectRequest\x1a/.haas.hardware.v1.ProjectResourceStatusResponse\"\x00\x42!Z\x1fgithub.com/haas/gen/hardware/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.hardware.hardware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037github.com/haas/gen/hardware/v1'
  _globals['_GETHARDWAREREQUEST']._serialized_start=111
  _globals['_GETHARDWAREREQUEST']._serialized_end=150
  _globals['_HARDWAREREQUEST']._serialized_start=152
  _globals['_HARDWAREREQUEST']._serialized_end=226
  _globals['_HARDWARE']._serialized_start=229
  _globals['_HARDWARE']._serialized_end=378
  _globals['_HARDWARELISTRESPONSE']._serialized_start=380
  _globals['_HARDWARELISTRESPONSE']._serialized_end=453
  _globals['_PROJECTREQUEST']._serialized_start=455
  _globals['_PROJECTREQUEST']._serialized_end=491
  _globals['_PROJECTRESOURCESTATUS']._serialized_start=493
  _globals['_PROJECTRESOURCESTATUS']._serialized_end=616
  _globals['_PROJECTRESOURCESTATUSRESPONSE']._serialized_start=618
  _globals['_PROJECTRESOURCESTATUSRESPONSE']._serialized_end=709
  _globals['_HARDWARESERVICE']._serialized_start=712
  _globals['_HARDWARESERVICE']._serialized_end=1182
# @@protoc_insertion_point(module_scope)
