apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask
  namespace: haas
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
