# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.projects import project_pb2 as api_dot_projects_dot_project__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/projects/project_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProject = channel.unary_unary(
                '/ProjectService/CreateProject',
                request_serializer=api_dot_projects_dot_project__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=api_dot_projects_dot_project__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/ProjectService/ListProjects',
                request_serializer=api_dot_projects_dot_project__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=api_dot_projects_dot_project__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/ProjectService/GetProject',
                request_serializer=api_dot_projects_dot_project__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=api_dot_projects_dot_project__pb2.GetProjectResponse.FromString,
                _registered_method=True)
        self.JoinProject = channel.unary_unary(
                '/ProjectService/JoinProject',
                request_serializer=api_dot_projects_dot_project__pb2.JoinProjectRequest.SerializeToString,
                response_deserializer=api_dot_projects_dot_project__pb2.JoinProjectResponse.FromString,
                _registered_method=True)
        self.LeaveProject = channel.unary_unary(
                '/ProjectService/LeaveProject',
                request_serializer=api_dot_projects_dot_project__pb2.LeaveProjectRequest.SerializeToString,
                response_deserializer=api_dot_projects_dot_project__pb2.LeaveProjectResponse.FromString,
                _registered_method=True)
        self.CheckUserInProject = channel.unary_unary(
                '/ProjectService/CheckUserInProject',
                request_serializer=api_dot_projects_dot_project__pb2.CheckUserInProjectRequest.SerializeToString,
                response_deserializer=api_dot_projects_dot_project__pb2.CheckUserInProjectResponse.FromString,
                _registered_method=True)
        self.ValidateProject = channel.unary_unary(
                '/ProjectService/ValidateProject',
                request_serializer=api_dot_projects_dot_project__pb2.ValidateProjectRequest.SerializeToString,
                response_deserializer=api_dot_projects_dot_project__pb2.ValidateProjectResponse.FromString,
                _registered_method=True)


class ProjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserInProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=api_dot_projects_dot_project__pb2.CreateProjectRequest.FromString,
                    response_serializer=api_dot_projects_dot_project__pb2.CreateProjectResponse.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=api_dot_projects_dot_project__pb2.ListProjectsRequest.FromString,
                    response_serializer=api_dot_projects_dot_project__pb2.ListProjectsResponse.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=api_dot_projects_dot_project__pb2.GetProjectRequest.FromString,
                    response_serializer=api_dot_projects_dot_project__pb2.GetProjectResponse.SerializeToString,
            ),
            'JoinProject': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinProject,
                    request_deserializer=api_dot_projects_dot_project__pb2.JoinProjectRequest.FromString,
                    response_serializer=api_dot_projects_dot_project__pb2.JoinProjectResponse.SerializeToString,
            ),
            'LeaveProject': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveProject,
                    request_deserializer=api_dot_projects_dot_project__pb2.LeaveProjectRequest.FromString,
                    response_serializer=api_dot_projects_dot_project__pb2.LeaveProjectResponse.SerializeToString,
            ),
            'CheckUserInProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserInProject,
                    request_deserializer=api_dot_projects_dot_project__pb2.CheckUserInProjectRequest.FromString,
                    response_serializer=api_dot_projects_dot_project__pb2.CheckUserInProjectResponse.SerializeToString,
            ),
            'ValidateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateProject,
                    request_deserializer=api_dot_projects_dot_project__pb2.ValidateProjectRequest.FromString,
                    response_serializer=api_dot_projects_dot_project__pb2.ValidateProjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ProjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectService/CreateProject',
            api_dot_projects_dot_project__pb2.CreateProjectRequest.SerializeToString,
            api_dot_projects_dot_project__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectService/ListProjects',
            api_dot_projects_dot_project__pb2.ListProjectsRequest.SerializeToString,
            api_dot_projects_dot_project__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectService/GetProject',
            api_dot_projects_dot_project__pb2.GetProjectRequest.SerializeToString,
            api_dot_projects_dot_project__pb2.GetProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectService/JoinProject',
            api_dot_projects_dot_project__pb2.JoinProjectRequest.SerializeToString,
            api_dot_projects_dot_project__pb2.JoinProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectService/LeaveProject',
            api_dot_projects_dot_project__pb2.LeaveProjectRequest.SerializeToString,
            api_dot_projects_dot_project__pb2.LeaveProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserInProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectService/CheckUserInProject',
            api_dot_projects_dot_project__pb2.CheckUserInProjectRequest.SerializeToString,
            api_dot_projects_dot_project__pb2.CheckUserInProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectService/ValidateProject',
            api_dot_projects_dot_project__pb2.ValidateProjectRequest.SerializeToString,
            api_dot_projects_dot_project__pb2.ValidateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
