# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/auth/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/auth/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pi/auth/user.proto\x12\thaas.user\"E\n\x0fRegisterRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x10RegisterResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0cLoginRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\";\n\rLoginResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x0b\n\tMeRequest\"K\n\nMeResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t2\xc1\x01\n\x0bUserService\x12\x43\n\x08Register\x12\x1a.haas.user.RegisterRequest\x1a\x1b.haas.user.RegisterResponse\x12:\n\x05Login\x12\x17.haas.user.LoginRequest\x1a\x18.haas.user.LoginResponse\x12\x31\n\x02Me\x12\x14.haas.user.MeRequest\x1a\x15.haas.user.MeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.auth.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=34
  _globals['_REGISTERREQUEST']._serialized_end=103
  _globals['_REGISTERRESPONSE']._serialized_start=105
  _globals['_REGISTERRESPONSE']._serialized_end=152
  _globals['_LOGINREQUEST']._serialized_start=154
  _globals['_LOGINREQUEST']._serialized_end=202
  _globals['_LOGINRESPONSE']._serialized_start=204
  _globals['_LOGINRESPONSE']._serialized_end=263
  _globals['_MEREQUEST']._serialized_start=265
  _globals['_MEREQUEST']._serialized_end=276
  _globals['_MERESPONSE']._serialized_start=278
  _globals['_MERESPONSE']._serialized_end=353
  _globals['_USERSERVICE']._serialized_start=356
  _globals['_USERSERVICE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
